### Es 1
Hai a disposizione un file `data.csv` contenente dati mensili di traffico aereo con due colonne:

- `date`: data in formato `YYYY-MM` (mese/anno)
- `passengers`: numero di passeggeri per quel mese


Costruisci un modello di **regressione polinomiale** che approssima l’andamento del numero di passeggeri nel tempo.

1. Carica il dataset.
2. Convertilo in un formato numerico utilizzando una colonna `mese_numerico` che conti i mesi a partire da gennaio 1949.
3. Applica una regressione polinomiale (grado a tua scelta).
4. Calcola l’RMSE tra i valori reali e quelli predetti.
5. Visualizza i dati reali e la curva stimata con Plotly.

In [14]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import PolynomialFeatures
from sklearn.pipeline import make_pipeline
import plotly.graph_objects as go
from sklearn.metrics import root_mean_squared_error
from sklearn.model_selection import train_test_split

df = pd.read_csv("data.csv")
df = df.dropna()
df

        date  passengers
0    1949-01       112.0
1    1949-02       118.0
2    1949-03       132.0
3    1949-04       129.0
4    1949-05       121.0
..       ...         ...
125  1960-07       622.0
126  1960-08       606.0
127  1960-09       508.0
128  1960-10       461.0
130  1960-12       432.0

[130 rows x 2 columns]

In [15]:
#converto in un formato numerico le date
df["mese_numerico"] = df.index+1
df

        date  passengers  mese_numerico
0    1949-01       112.0              1
1    1949-02       118.0              2
2    1949-03       132.0              3
3    1949-04       129.0              4
4    1949-05       121.0              5
..       ...         ...            ...
125  1960-07       622.0            126
126  1960-08       606.0            127
127  1960-09       508.0            128
128  1960-10       461.0            129
130  1960-12       432.0            131

[130 rows x 3 columns]

In [ ]:
#regressione lineare
import scipy as sp

def polinomio_3_grado (x, a, b, c, d):
    return a*x**3+b*x**2+c*x+d

months = df["mese_numerico"]
passengers = df["passengers"]
fitable_curve, _ = sp.optimize.curve_fit(polinomio_3_grado, months, passengers)

array([-9.31604167e-05,  2.62635637e-02,  1.05267963e+00,  1.15544022e+02])

In [ ]:
#calcolare RMSE
pred_values = polinomio_3_grado(months, *fitable_curve)
rmse = np.sqrt(np.mean((passengers-pred_values)**2))

np.float64(45.10933571813696)

In [25]:
#plottare
fig = go.Figure()
fig.add_trace(go.Scatter(x = months, y = passengers, name = "Passeggeri",
                        line = dict(color = "blue", width = 4)))
fig.add_trace(go.Scatter(x = months, y = pred_values, name = "Predizione",
                        line = dict(color = "red", width = 2)))
fig.update_layout(
    title = "Passeggeri mensili",
    xaxis_title = "Mesi",
    yaxis_title = "Numero di passeggeri",
)
fig.show()